services:
  db:
    image: postgres:13.0-alpine
    platform: linux/amd64
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - foodgram_network

  backend:
    image: mregor123/foodgram_backend:latest
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - static_value:/app/collected_static/
      - media_value:/app/media/
      - redoc:/redoc/
    networks:
      - foodgram_network

  nginx:
    image: nginx:1.21.3-alpine
    platform: linux/amd64
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html/:ro
      - static_value:/app/collected_static/
      - media_value:/app/media/
      - redoc:/redoc/
    networks:
      - foodgram_network

volumes:
  postgres_data:
  static_value:
  media_value:
  redoc:

networks:
  foodgram_network:
    driver: bridge