version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks:
      - foodgram_network

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:latest
    platform: linux/amd64
    restart: always
    volumes:
      - static_value:/app/collected_static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - foodgram_network

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:latest
    platform: linux/amd64
    volumes:
     - ../frontend/build:/app/result_build/
    networks:
      - foodgram_network

  nginx:
    image: nginx:1.21.3-alpine
    platform: linux/amd64
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/yc-user/foodgram/foodgramproject.crt:/etc/nginx/foodgramproject.crt
      - /home/yc-user/foodgram/foodgramproject.key:/etc/nginx/foodgramproject.key
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/app/collected_static/
      - media_value:/app/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - foodgram_network

volumes:
  static_value:
  media_value:
  postgres_data:
  redoc:

networks:
  foodgram_network:
    driver: bridge